spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.110.151.136:3306/sell?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true

  redis:
    host: 47.110.151.136
    port: 6379
    password: 1qaz@WSX1qaz
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell
  port: 80
